version: '3.0'
services:

  postgresda:
    image: "postgres:alpine"
    container_name: postgresda
    volumes:
      - DAdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=daily_activitie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=74868726
      - APP_DB_User=dockers
    networks:
      - postgres1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./be
    container_name: be
    image: be
    environment:
      - DB_SERVER=postgresda
    ports:
      - 3011:3011
    networks:
      - postgres1
    depends_on:
      - postgresda
      
   
  frontend:
    build: ./fe
    container_name: fe
    image: fe
    ports:
      - 3000:3000
    networks:
      - postgres1     


networks:
  postgres1:
    driver: bridge

volumes:
  DAdata:
